### ISSUE TITLE
Error when working with non existing channels

### ISSUE THREAD

**Issue by pavelsc** [asterisk/node-ari-client#17]
For example when I got channelHangupRequest I want to hangup other party of a call. But the other party already could be hanged up due to transfer (e.g. without hangup request). So when i try to manipulate this channel by id I get uncatchable error:
>/var/daemon/node_modules/ari-client/lib/client.js:244
          userCallback(err);
          ^
TypeError: object is not a function
    at swaggerError [as errorCallback] (/var/daemon/node_modules/ari-client/lib/client.js:244:11)
    at Object.obj.on.error (/var/daemon/node_modules/ari-client/node_modules/swagger-client/lib/swagger.js:1077:24)
    at EventEmitter.res.error (/var/daemon/node_modules/ari-client/node_modules/swagger-client/lib/swagger.js:1296:19)
    at EventEmitter.emit (events.js:109:17)
    at emit (/var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:454:21)
    at /var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:473:9
    at setBodyAndFinish (/var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:103:7)
    at IncomingMessage.<anonymous> (/var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:120:7)
    at IncomingMessage.emit (events.js:131:20)
    at _stream_readable.js:910:16

Yea, I know I should take care of that and prevent the use of non-existing channels but from the other side my worker can crash and stop if non existing channeld is used in `ari.channels.hangup({})`. Let me know if you consider this is an issue or not. Thanks in advance!

**Comment by samuelg** [comment]
The issue here is that you did not provide a callback to handle an error/success scenario.

```JavaScript
ari.channels.hangup({channelId: 1}, function(err) {});
```
This will ignore any errors that result from calling hangup.

**Comment by pavelsc** [comment]
That works for some cases. But in case when I'am trying to hangup channels with callback in a holding bridge it doesn't work. Another error:

>/var/daemon/node_modules/ari-client/lib/resources.js:901
        userCallback(err);
        ^
TypeError: object is not a function
    at swaggerError [as errorCallback] (/var/daemon/node_modules/ari-client/lib/resources.js:901:9)
    at Object.obj.on.error (/var/daemon/node_modules/ari-client/node_modules/swagger-client/lib/swagger.js:1077:24)
    at EventEmitter.res.error (/var/daemon/node_modules/ari-client/node_modules/swagger-client/lib/swagger.js:1296:19)
    at EventEmitter.emit (events.js:107:17)
    at emit (/var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:454:21)
    at /var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:473:9
    at setBodyAndFinish (/var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:103:7)
    at IncomingMessage.<anonymous> (/var/daemon/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:120:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

Thanks!

**Comment by samuelg** [comment]
Can you provide the code you are running that causes this? This error occurs when a callback is either not provided or is not a function.

**Comment by pavelsc** [comment]
Hm, ok I have found some interesting. Some functions works but always throws `null` error, for example ari.bridges.record starts recording but anyway throws an error (beware this if you are using Q.defer). So I put callbacks in all node-ari functions and it helps me.
```
self.parent.ari.client.bridges.record({
	bridgeId: call.bridge.id,
	name: path,
	format: 'wav'
}, function (err) {
	if (err) {
		console.log(err);
	}
});
```

**Comment by samuelg** [comment]
That is a Node.js convention. If no errors occurred, null is returned as the first argument to the provided callback. It doesn't mean that an error occurred.

If you are using Q, you can use Q.denodeify() to call the ari-client operation which will return a promise that you can then call .then() or .catch() on. For denodeified calls, the catch() function will only be called if an actual error occurred.
