### ISSUE TITLE
ari.channels.create() and ari.channels.dial() function not working

### ISSUE THREAD

**Issue by mpbanna** [asterisk/node-ari-client#83]
Hello ,
I am talking about issue #77.
In this issue i am using ari.channels.create() then ari.channels.dial() but it gives type error:

/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: client.channels.create is not a function
    at clientLoaded (/usr/local/lib/node_modules/sarvIVR/IVR/mahi_callTransfer.js:163:25)
    at tryCatcher (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/ari-client/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by ruffrey** [comment]
Hi mpbanna, will you post a sample of the code you are using before the error happens?

**Comment by jcolp** [comment]
As well, what version of Asterisk are you using? The create/dial functionality is only present in Asterisk 14.

**Comment by mpbanna** [comment]
all right , i am using old version of asterisk , now i upgrade it to asterisk 14 and it working.
