### ISSUE TITLE
Error with Asterisk 14.7.0-rc1

### ISSUE THREAD

**Issue by jaunis** [asterisk/node-ari-client#98]
The node-ari-client library is not working any more with Asterisk 14.7.0-rc1. It is failing during initialization with the following error :
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.obj.on.response (/usr/lib/node_modules/ari-client/node_modules/swagger-client/lib/swagger.js:136:44)
    at EventEmitter.res.response (/usr/lib/node_modules/ari-client/node_modules/swagger-client/lib/swagger.js:1309:19)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at emit (/usr/lib/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:457:21)
    at /usr/lib/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:477:9
    at setBodyAndFinish (/usr/lib/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:103:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/ari-client/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:120:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

I think it is due to Asterisk sending the HTTP headers and the body in two separate TCP packets. The issue is probably not on the Asterisk side, since standard tools like CURL are able to handle the response.

Everything was working fine until Asterisk 14.6.2.

**Comment by jaunis** [comment]
Well, maybe this has been fixed in 14.7.0-rc2 (see https://issues.asterisk.org/jira/browse/ASTERISK-27372). I will test it as soon as I can and keep you informed.

**Comment by asteriskteam** [comment]
Hey jaunis,

That issue has a patch that's been pushed through Gerrit (
https://gerrit.asterisk.org/#/c/6912/). It should fix your problems with
ARI client. I hope this helps.

Ben Ford

**Comment by jaunis** [comment]
I've tested with version 14.7.2, it's working. Thanks a lot !
